apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blobfuse
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-blobfuse
  storageClassName: azureblob-fuse-premium
